### ISSUE TITLE
Need a provision to edit customer's card details

### ISSUE THREAD

**Issue by pbharadiya** [razorpay/razorpay-ruby#57]
Hello Team,

We would like to have a provision to edit customer's card details via customer id.
Flow could be as follow:
1. We will ask customer to provide card details that they want to update. (On failed subscription or to update card details)
2. We will send API request to Razorpay to authenticate new card details.
3. On successful authorisation, Razorpay would send success message and we will update new razorpay_card_id to our system.
4. Finally, subsequent subscription should be charged from new card details.

This would be very helpful for us to provide ease to our customers.

Thanks in advance!

**Comment by pikender** [comment]
@pbharadiya I fail to find the reference in docs but whenever a charge is failed on the subscription card, customer gets a mail for failed charge and in that mail, there is a link through which customer can either change the card or activate the card again ( for e.g. if charge failed due to insufficient balance or some temporary hiccup with given card )

![failed-razorpay-subscription-charge-1](https://user-images.githubusercontent.com/804609/36727163-477ecbf4-1be2-11e8-949c-7c6d5b47531e.png)


cc/ @harman28 @captn3m0 @StSarc

**Comment by captn3m0** [comment]
Sorry about the delay here. We try to only keep ruby-SDK related issues here and this got missed out.

@pbharadiya Sending you an email regarding this.

@pikender thanks for popping this thread :+1:. I'm marking this as closed and taking it over email instead.
