### ISSUE TITLE
Integrate sub merchant 

### ISSUE THREAD

**Issue by dharshann** [razorpay/razorpay-ruby#86]
How would you suggest using this library for both normal and a sub-merchant account transactions?

Currently `razorpay-ruby` gem is setup-ed with an initializer with single user/merchant's credentials.

Is it a good way to explicitly setup/override Razorpay with sub-merchant's credentials wherever we are require sub-merchant instance
```
  id = Rails.application.secrets.razorpay['sub_merchant_id']
  secret = Rails.application.secrets.razorpay['sub_merchant_secret']

  Razorpay.setup(id, secret)

  Razorpay::Orders.all
  ...
```

**Comment by harman28** [comment]
@dharshann It's been [called out before](https://github.com/razorpay/razorpay-ruby/issues/66) that this gem isn't thread-safe, i.e. because the config is set just once and reused by all functions, it's not possible to use multiple merchant accounts in the same app. There are hacks that might work (maybe a local clone of the gem, after which the 2 gems can be used for separate accounts), but essentially this isn't supported right now. 

We've got it on our roadmap though and hope to be able to get this done sometime later this year (pull requests are welcome!).

**Comment by harman28** [comment]
I'd like to close this as basically a duplicate of #66. Let me know if this^ answers your question.

**Comment by dharshann** [comment]
@harman28 didn't see the open issue. Hoping to see suggested changes in new release.
